// Complete Nigerian Location Data for Landlord App
// Structure: nigeriaStates[], stateLGAs{}, lgaAreas{}

export const nigeriaStates = [
  'Abia', 'Adamawa', 'Akwa Ibom', 'Anambra', 'Bauchi', 'Bayelsa', 'Benue', 'Borno',
  'Cross River', 'Delta', 'Ebonyi', 'Edo', 'Ekiti', 'Enugu', 'Abuja', 'Gombe', 'Imo',
  'Jigawa', 'Kaduna', 'Kano', 'Katsina', 'Kebbi', 'Kogi', 'Kwara', 'Lagos', 'Nasarawa',
  'Niger', 'Ogun', 'Ondo', 'Osun', 'Oyo', 'Plateau', 'Rivers', 'Sokoto', 'Taraba',
  'Yobe', 'Zamfara'
];

export const stateLGAs = {
  'Abia': ['Aba North', 'Aba South', 'Arochukwu', 'Bende', 'Ikwuano', 'Isiala Ngwa North', 'Isiala Ngwa South', 'Isuikwuato', 'Obi Ngwa', 'Ohafia', 'Osisioma', 'Ugwunagbo', 'Ukwa East', 'Ukwa West', 'Umuahia North', 'Umuahia South', 'Umu Nneochi'],
  'Adamawa': ['Demsa', 'Fufure', 'Ganye', 'Gayuk', 'Gombi', 'Grie', 'Hong', 'Jada', 'Lamurde', 'Madagali', 'Maiha', 'Mayo Belwa', 'Michika', 'Mubi North', 'Mubi South', 'Numan', 'Shelleng', 'Song', 'Toungo', 'Yola North', 'Yola South'],
  'Akwa Ibom': ['Abak', 'Eastern Obolo', 'Eket', 'Esit Eket', 'Essien Udim', 'Etim Ekpo', 'Etinan', 'Ibeno', 'Ibesikpo Asutan', 'Ibiono-Ibom', 'Ika', 'Ikono', 'Ikot Abasi', 'Ikot Ekpene', 'Ini', 'Itu', 'Mbo', 'Mkpat-Enin', 'Nsit-Atai', 'Nsit-Ibom', 'Nsit-Ubium', 'Obot Akara', 'Okobo', 'Onna', 'Oron', 'Oruk Anam', 'Udung-Uko', 'Ukanafun', 'Uruan', 'Urue-Offong/Oruko', 'Uyo'],
  'Anambra': ['Aguata', 'Anambra East', 'Anambra West', 'Anaocha', 'Awka North', 'Awka South', 'Ayamelum', 'Dunukofia', 'Ekwusigo', 'Idemili North', 'Idemili South', 'Ihiala', 'Njikoka', 'Nnewi North', 'Nnewi South', 'Ogbaru', 'Onitsha North', 'Onitsha South', 'Orumba North', 'Orumba South', 'Oyi'],
  'Bauchi': ['Alkaleri', 'Bauchi', 'Bogoro', 'Damban', 'Darazo', 'Dass', 'Gamawa', 'Ganjuwa', 'Giade', 'Itas/Gadau', "Jama'are", 'Katagum', 'Kirfi', 'Misau', 'Ningi', 'Shira', 'Tafawa Balewa', 'Toro', 'Warji', 'Zaki'],
  'Bayelsa': ['Brass', 'Ekeremor', 'Kolokuma/Opokuma', 'Nembe', 'Ogbia', 'Sagbama', 'Southern Ijaw', 'Yenagoa'],
  'Benue': ['Ado', 'Agatu', 'Apa', 'Buruku', 'Gboko', 'Guma', 'Gwer East', 'Gwer West', 'Katsina-Ala', 'Konshisha', 'Kwande', 'Logo', 'Makurdi', 'Obi', 'Ogbadibo', 'Ohimini', 'Oju', 'Okpokwu', 'Oturkpo', 'Tarka', 'Ukum', 'Ushongo', 'Vandeikya'],
  'Borno': ['Abadam', 'Askira/Uba', 'Bama', 'Bayo', 'Biu', 'Chibok', 'Damboa', 'Dikwa', 'Gubio', 'Guzamala', 'Gwoza', 'Hawul', 'Jere', 'Kaga', 'Kala/Balge', 'Konduga', 'Kukawa', 'Kwaya Kusar', 'Mafa', 'Magumeri', 'Maiduguri', 'Marte', 'Mobbar', 'Monguno', 'Ngala', 'Nganzai', 'Shani'],
  'Cross River': ['Abi', 'Akamkpa', 'Akpabuyo', 'Bakassi', 'Bekwarra', 'Biase', 'Boki', 'Calabar Municipal', 'Calabar South', 'Etung', 'Ikom', 'Obanliku', 'Obubra', 'Obudu', 'Odukpani', 'Ogoja', 'Yakuur', 'Yala'],
  'Delta': ['Aniocha North', 'Aniocha South', 'Bomadi', 'Burutu', 'Ethiope East', 'Ethiope West', 'Ika North East', 'Ika South', 'Isoko North', 'Isoko South', 'Ndokwa East', 'Ndokwa West', 'Okpe', 'Oshimili North', 'Oshimili South', 'Patani', 'Sapele', 'Udu', 'Ughelli North', 'Ughelli South', 'Ukwuani', 'Uvwie', 'Warri North', 'Warri South', 'Warri South West'],
  'Ebonyi': ['Abakaliki', 'Afikpo North', 'Afikpo South', 'Ebonyi', 'Ezza North', 'Ezza South', 'Ikwo', 'Ishielu', 'Ivo', 'Izzi', 'Ohaozara', 'Ohaukwu', 'Onicha'],
  'Edo': ['Akoko-Edo', 'Egor', 'Esan Central', 'Esan North-East', 'Esan South-East', 'Esan West', 'Etsako Central', 'Etsako East', 'Etsako West', 'Igueben', 'Ikpoba Okha', 'Oredo', 'Orhionmwon', 'Ovia North-East', 'Ovia South-West', 'Owan East', 'Owan West', 'Uhunmwonde'],
  'Ekiti': ['Ado Ekiti', 'Efon', 'Ekiti East', 'Ekiti South-West', 'Ekiti West', 'Emure', 'Gbonyin', 'Ido Osi', 'Ijero', 'Ikere', 'Ikole', 'Ilejemeje', 'Irepodun/Ifelodun', 'Ise/Orun', 'Moba', 'Oye'],
  'Enugu': ['Aninri', 'Awgu', 'Enugu East', 'Enugu North', 'Enugu South', 'Ezeagu', 'Igbo Etiti', 'Igbo Eze North', 'Igbo Eze South', 'Isi Uzo', 'Nkanu East', 'Nkanu West', 'Nsukka', 'Oji River', 'Udenu', 'Udi', 'Uzo Uwani'],
  'Abuja': ['Abaji', 'AMAC', 'Bwari', 'Gwagwalada', 'Kuje', 'Kwali'],
  'Gombe': ['Akko', 'Balanga', 'Billiri', 'Dukku', 'Funakaye', 'Gombe', 'Kaltungo', 'Kwami', 'Nafada', 'Shongom', 'Yamaltu/Deba'],
  'Imo': ['Aboh Mbaise', 'Ahiazu Mbaise', 'Ehime Mbano', 'Ezinihitte', 'Ideato North', 'Ideato South', 'Ihitte/Uboma', 'Ikeduru', 'Isiala Mbano', 'Isu', 'Mbaitoli', 'Ngor Okpala', 'Njaba', 'Nkwerre', 'Nwangele', 'Obowo', 'Oguta', 'Ohaji/Egbema', 'Okigwe', 'Onuimo', 'Orlu', 'Orsu', 'Oru East', 'Oru West', 'Owerri Municipal', 'Owerri North', 'Owerri West'],
  'Jigawa': ['Auyo', 'Babura', 'Biriniwa', 'Birnin Kudu', 'Buji', 'Dutse', 'Gagarawa', 'Garki', 'Gumel', 'Guri', 'Gwaram', 'Gwiwa', 'Hadejia', 'Jahun', 'Kafin Hausa', 'Kaugama', 'Kazaure', 'Kiri Kasama', 'Kiyawa', 'Maigatari', 'Malam Madori', 'Miga', 'Ringim', 'Roni', 'Sule Tankarkar', 'Taura', 'Yankwashi'],
  'Kaduna': ['Birnin Gwari', 'Chikun', 'Giwa', 'Igabi', 'Ikara', 'Jaba', "Jema'a", 'Kachia', 'Kaduna North', 'Kaduna South', 'Kagarko', 'Kajuru', 'Kaura', 'Kauru', 'Kubau', 'Kudan', 'Lere', 'Makarfi', 'Sabon Gari', 'Sanga', 'Soba', 'Zangon Kataf', 'Zaria'],
  'Kano': ['Ajingi', 'Albasu', 'Bagwai', 'Bebeji', 'Bichi', 'Bunkure', 'Dala', 'Dambatta', 'Dawakin Kudu', 'Dawakin Tofa', 'Doguwa', 'Fagge', 'Gabasawa', 'Garko', 'Garun Mallam', 'Gaya', 'Gezawa', 'Gwale', 'Gwarzo', 'Kabo', 'Kano Municipal', 'Karaye', 'Kibiya', 'Kiru', 'Kumbotso', 'Kunchi', 'Kura', 'Madobi', 'Makoda', 'Minjibir', 'Nasarawa', 'Rano', 'Rimin Gado', 'Rogo', 'Shanono', 'Sumaila', 'Takai', 'Tarauni', 'Tofa', 'Tsanyawa', 'Tudun Wada', 'Ungogo', 'Warawa', 'Wudil'],
  'Katsina': ['Bakori', 'Batagarawa', 'Batsari', 'Baure', 'Bindawa', 'Charanchi', 'Dandume', 'Danja', 'Dan Musa', 'Daura', 'Dutsi', 'Dutsin Ma', 'Faskari', 'Funtua', 'Ingawa', 'Jibia', 'Kafur', 'Kaita', 'Kankara', 'Kankia', 'Katsina', 'Kurfi', 'Kusada', "Mai'Adua", 'Malumfashi', 'Mani', 'Mashi', 'Matazu', 'Musawa', 'Rimi', 'Sabuwa', 'Safana', 'Sandamu', 'Zango'],
  'Kebbi': ['Aleiro', 'Arewa Dandi', 'Argungu', 'Augie', 'Bagudo', 'Birnin Kebbi', 'Bunza', 'Dandi', 'Fakai', 'Gwandu', 'Jega', 'Kalgo', 'Koko/Besse', 'Maiyama', 'Ngaski', 'Sakaba', 'Shanga', 'Suru', 'Wasagu/Danko', 'Yauri', 'Zuru'],
  'Kogi': ['Adavi', 'Ajaokuta', 'Ankpa', 'Bassa', 'Dekina', 'Ibaji', 'Idah', 'Igalamela Odolu', 'Ijumu', 'Kabba/Bunu', 'Kogi', 'Lokoja', 'Mopa Muro', 'Ofu', 'Ogori/Magongo', 'Okehi', 'Okene', 'Olamaboro', 'Omala', 'Yagba East', 'Yagba West'],
  'Kwara': ['Asa', 'Baruten', 'Edu', 'Ekiti', 'Ifelodun', 'Ilorin East', 'Ilorin South', 'Ilorin West', 'Irepodun', 'Isin', 'Kaiama', 'Moro', 'Offa', 'Oke Ero', 'Oyun', 'Pategi'],
  'Lagos': ['Agege', 'Ajeromi-Ifelodun', 'Alimosho', 'Amuwo-Odofin', 'Apapa', 'Badagry', 'Epe', 'Eti-Osa', 'Ibeju-Lekki', 'Ifako-Ijaiye', 'Ikeja', 'Ikorodu', 'Kosofe', 'Lagos Island', 'Lagos Mainland', 'Mushin', 'Ojo', 'Oshodi-Isolo', 'Shomolu', 'Surulere'],
  'Nasarawa': ['Akwanga', 'Awe', 'Doma', 'Karu', 'Keana', 'Keffi', 'Kokona', 'Lafia', 'Nasarawa', 'Nasarawa Egon', 'Obi', 'Toto', 'Wamba'],
  'Niger': ['Agaie', 'Agwara', 'Bida', 'Borgu', 'Bosso', 'Chanchaga', 'Edati', 'Gbako', 'Gurara', 'Katcha', 'Kontagora', 'Lapai', 'Lavun', 'Magama', 'Mariga', 'Mashegu', 'Mokwa', 'Moya', 'Paikoro', 'Rafi', 'Rijau', 'Shiroro', 'Suleja', 'Tafa', 'Wushishi'],
  'Ogun': ['Abeokuta North', 'Abeokuta South', 'Ado-Odo/Ota', 'Egbado North', 'Egbado South', 'Ewekoro', 'Ifo', 'Ijebu East', 'Ijebu North', 'Ijebu North East', 'Ijebu Ode', 'Ikenne', 'Imeko Afon', 'Ipokia', 'Obafemi Owode', 'Odeda', 'Odogbolu', 'Ogun Waterside', 'Remo North', 'Shagamu'],
  'Ondo': ['Akoko North-East', 'Akoko North-West', 'Akoko South-West', 'Akoko South-East', 'Akure North', 'Akure South', 'Ese Odo', 'Idanre', 'Ifedore', 'Ilaje', 'Ile Oluji/Okeigbo', 'Irele', 'Odigbo', 'Okitipupa', 'Ondo East', 'Ondo West', 'Ose', 'Owo'],
  'Osun': ['Atakunmosa East', 'Atakunmosa West', 'Aiyedaade', 'Aiyedire', 'Boluwaduro', 'Boripe', 'Ede North', 'Ede South', 'Egbedore', 'Ejigbo', 'Ife Central', 'Ife East', 'Ife North', 'Ife South', 'Ifedayo', 'Ifelodun', 'Ila', 'Ilesa East', 'Ilesa West', 'Irepodun', 'Irewole', 'Isokan', 'Iwo', 'Obokun', 'Odo Otin', 'Ola Oluwa', 'Olorunda', 'Oriade', 'Orolu', 'Osogbo'],
  'Oyo': ['Afijio', 'Akinyele', 'Atiba', 'Atisbo', 'Egbeda', 'Ibadan North', 'Ibadan North-East', 'Ibadan North-West', 'Ibadan South-East', 'Ibadan South-West', 'Ibarapa Central', 'Ibarapa East', 'Ibarapa North', 'Ido', 'Irepo', 'Iseyin', 'Itesiwaju', 'Iwajowa', 'Kajola', 'Lagelu', 'Ogbomosho North', 'Ogbomosho South', 'Ogo Oluwa', 'Olorunsogo', 'Oluyole', 'Ona Ara', 'Orelope', 'Ori Ire', 'Oyo East', 'Oyo West', 'Saki East', 'Saki West', 'Surulere'],
  'Plateau': ['Barkin Ladi', 'Bassa', 'Bokkos', 'Jos East', 'Jos North', 'Jos South', 'Kanam', 'Kanke', 'Langtang North', 'Langtang South', 'Mangu', 'Mikang', 'Pankshin', "Qua'an Pan", 'Riyom', 'Shendam', 'Wase'],
  'Rivers': ['Abua/Odual', 'Ahoada East', 'Ahoada West', 'Akuku-Toru', 'Andoni', 'Asari-Toru', 'Bonny', 'Degema', 'Eleme', 'Emohua', 'Etche', 'Gokana', 'Ikwerre', 'Khana', 'Obio/Akpor', 'Ogba/Egbema/Ndoni', 'Ogu/Bolo', 'Okrika', 'Omuma', 'Opobo/Nkoro', 'Oyigbo', 'Port Harcourt', 'Tai'],
  'Sokoto': ['Binji', 'Bodinga', 'Dange Shuni', 'Gada', 'Goronyo', 'Gudu', 'Gwadabawa', 'Illela', 'Isa', 'Kebbe', 'Kware', 'Rabah', 'Sabon Birni', 'Shagari', 'Silame', 'Sokoto North', 'Sokoto South', 'Tambuwal', 'Tangaza', 'Tureta', 'Wamako', 'Wurno', 'Yabo'],
  'Taraba': ['Ardo Kola', 'Bali', 'Donga', 'Gashaka', 'Gassol', 'Ibi', 'Jalingo', 'Karim Lamido', 'Kumi', 'Lau', 'Sardauna', 'Takum', 'Ussa', 'Wukari', 'Yorro', 'Zing'],
  'Yobe': ['Bade', 'Bursari', 'Damaturu', 'Fika', 'Fune', 'Geidam', 'Gujba', 'Gulani', 'Jakusko', 'Karasuwa', 'Machina', 'Nangere', 'Nguru', 'Potiskum', 'Tarmuwa', 'Yunusari', 'Yusufari'],
  'Zamfara': ['Anka', 'Bakura', 'Birnin Magaji/Kiyaw', 'Bukkuyum', 'Bungudu', 'Gummi', 'Gusau', 'Kaura Namoda', 'Maradun', 'Maru', 'Shinkafi', 'Talata Mafara', 'Chafe', 'Zurmi']
};

export const lgaAreas = {
  'Abia': {
    'Aba North': ['Eziama', 'Ogbor Hill', 'Osusu'],
    'Aba South': ['Aba GRA', 'Faulks Road', 'Azikiwe Road', 'Factory Road'],
    'Umuahia North': ['Umuahia GRA', 'Library Avenue', 'Aba Road', 'World Bank'],
    'Umuahia South': ['Ubakala', 'Nsulu', 'Apumiri'],
    'Ohafia': ['Ohafia Town', 'Abiriba'],
    'Osisioma': ['Osisioma Town', 'Aba-Owerri Road'],
  },
  'Adamawa': {
    'Yola North': ['Jimeta', 'Yola GRA', 'Karewa', 'Demsawo'],
    'Yola South': ['Yola Town', 'Namtari', 'Adarawo'],
    'Mubi North': ['Mubi Town', 'Lokuwa', 'Kolere'],
    'Numan': ['Numan Town', 'Numan GRA'],
    'Ganye': ['Ganye Town', 'Sugu'],
  },
  'Akwa Ibom': {
    'Uyo': ['Uyo Town', 'Ewet Housing', 'Shelter Afrique', 'Aka Itiam', 'Four Lanes'],
    'Eket': ['Eket Town', 'QIT', 'Idua'],
    'Ikot Ekpene': ['Ikot Ekpene Town', 'Abia Street', 'Calabar Road'],
    'Oron': ['Oron Town', 'Udung Uko'],
    'Itu': ['Itu Town', 'Itam'],
  },
  'Anambra': {
    'Awka South': ['Awka GRA', 'Amawbia', 'Okpuno', 'Ifite'],
    'Onitsha North': ['Onitsha GRA', 'Inland Town', 'Fegge'],
    'Onitsha South': ['Woliwo', 'Odoakpu'],
    'Nnewi North': ['Nnewi Town', 'Uruagu', 'Otolo', 'Umudim'],
    'Idemili North': ['Ogidi', 'Nkpor', 'Obosi'],
  },
  'Bauchi': {
    'Bauchi': ['Bauchi GRA', 'Wunti', 'Yelwa', 'Federal Low Cost'],
    'Katagum': ['Azare', 'Katagum Town'],
    'Toro': ['Toro Town'],
  },
  'Bayelsa': {
    'Yenagoa': ['Yenagoa Town', 'Ovom', 'Swali', 'Biogbolo', 'Opolo', 'Amarata'],
    'Ogbia': ['Ogbia Town', 'Otuoke'],
    'Nembe': ['Nembe Town', 'Ogbolomabiri'],
  },
  'Benue': {
    'Makurdi': ['Makurdi GRA', 'High Level', 'Wadata', 'North Bank', 'Modern Market'],
    'Gboko': ['Gboko Town', 'Gboko South'],
    'Oturkpo': ['Otukpo Town', 'Otukpo GRA'],
  },
  'Borno': {
    'Maiduguri': ['Maiduguri GRA', 'Old GRA', 'London Ciki', 'Bolori', 'Gwange'],
    'Jere': ['Jere Town', 'Maimalari'],
    'Biu': ['Biu Town'],
  },
  'Cross River': {
    'Calabar Municipal': ['Calabar GRA', 'Marian', 'Watt Market', 'Diamond Hill', 'Henshaw Town'],
    'Calabar South': ['Calabar South', 'Anantigha', 'Ekpo Abasi'],
    'Ogoja': ['Ogoja Town'],
    'Obudu': ['Obudu Town', 'Obudu Ranch'],
  },
  'Delta': {
    'Warri South': ['Warri GRA', 'Effurun', 'NPA', 'Igbudu'],
    'Oshimili South': ['Asaba GRA', 'Cable Point', 'Okpanam', 'Summit Road', 'DBS Road'],
    'Uvwie': ['Effurun', 'Ekpan', 'Ugboroke'],
    'Ethiope East': ['Isiokolo', 'Abraka'],
    'Sapele': ['Sapele Town', 'Amukpe'],
    'Ughelli North': ['Ughelli Town', 'Agbarho'],
  },
  'Ebonyi': {
    'Abakaliki': ['Abakaliki Town', 'Kpirikpiri', 'Presco', 'Azugwu'],
    'Afikpo North': ['Afikpo Town', 'Unwana'],
    'Ikwo': ['Ikwo Town', 'Echara'],
  },
  'Edo': {
    'Oredo': ['GRA Benin City', 'Ring Road', 'Sapele Road', 'Uselu', 'Ugbor', 'Airport Road'],
    'Egor': ['Uselu', 'Ugbowo', 'Egor Town'],
    'Ikpoba Okha': ['Aduwawa', 'Oluku', 'Ikpoba Hill'],
    'Etsako West': ['Auchi', 'South Ibie'],
    'Esan Central': ['Irrua', 'Ewu'],
    'Ovia North-East': ['Okada', 'Ekiadolor'],
  },
  'Ekiti': {
    'Ado Ekiti': ['Ado Ekiti Town', 'Ajilosun', 'Basiri', 'Adebayo'],
    'Ikere': ['Ikere-Ekiti'],
    'Ijero': ['Ijero-Ekiti'],
    'Oye': ['Oye-Ekiti', 'Ayede'],
  },
  'Enugu': {
    'Enugu North': ['Independence Layout', 'New Haven', 'Ogui', 'GRA', 'Coal Camp'],
    'Enugu South': ['Achara Layout', 'Maryland', 'Trans Ekulu', 'Uwani'],
    'Enugu East': ['Nike', 'Abakpa', 'Emene'],
    'Nsukka': ['Nsukka Town', 'University of Nigeria'],
    'Udi': ['Udi Town', 'Ngwo'],
    'Nkanu West': ['Agbani'],
  },
  'Abuja': {
    'AMAC': ['Wuse 1', 'Wuse 2', 'Maitama', 'Asokoro', 'Garki', 'Central Area', 'Gwarinpa', 'Jabi', 'Life Camp', 'Utako', 'Wuye', 'Guzape', 'Katampe', 'Durumi'],
    'Bwari': ['Bwari Town', 'Kubwa', 'Dutse', 'Byazhin'],
    'Gwagwalada': ['Gwagwalada Town', 'Tunga Maje', 'Kutunku'],
    'Kuje': ['Kuje Town', 'Rubochi', 'Chibiri'],
    'Kwali': ['Kwali Town', 'Dafa'],
    'Abaji': ['Abaji Town', 'Toto'],
  },
  'Gombe': {
    'Gombe': ['Gombe Town', 'GRA', 'Federal Low Cost', 'Tudun Wada'],
    'Akko': ['Akko Town', 'Kumo'],
    'Kaltungo': ['Kaltungo Town'],
  },
  'Imo': {
    'Owerri Municipal': ['Owerri Town', 'Wetheral', 'Douglas Road', 'Royce Road'],
    'Owerri North': ['Naze', 'Ihiagwa', 'Avu'],
    'Owerri West': ['Umuguma', 'Obinze'],
    'Orlu': ['Orlu Town', 'Banana Junction'],
    'Okigwe': ['Okigwe Town', 'Umulolo'],
  },
  'Jigawa': {
    'Dutse': ['Dutse Town', 'Dutse GRA', 'Takur'],
    'Hadejia': ['Hadejia Town', 'Hadejia GRA'],
    'Gumel': ['Gumel Town'],
  },
  'Kaduna': {
    'Kaduna North': ['Malali', 'Ungwan Rimi', 'Kawo', 'Badarawa', 'Kabala Costain'],
    'Kaduna South': ['Barnawa', 'Kakuri', 'Tudun Wada', 'Television', 'Sabon Tasha'],
    'Chikun': ['Narayi', 'Gonin Gora', 'Sabon Tasha', 'Kakau'],
    'Igabi': ['Rigasa', 'Turunku', 'Afaka'],
    'Zaria': ['Zaria City', 'Samaru', 'Sabon Gari Zaria', 'Tudun Wada Zaria'],
    "Jema'a": ['Kafanchan', 'Kagoro'],
  },
  'Kano': {
    'Kano Municipal': ['Sabon Gari', 'Fagge', 'Dala', 'Nassarawa GRA', 'Bompai', 'Zoo Road'],
    'Gwale': ['Gwale Town', 'Goron Dutse'],
    'Tarauni': ['Hotoro', 'Gadon Kaya', 'Tarauni Town'],
    'Fagge': ['Fagge Town', 'Sabon Gari Kano', 'France Road'],
    'Ungogo': ['Ungogo Town', 'Rijiyar Zaki'],
    'Kumbotso': ['Kumbotso Town', 'Panshekara'],
  },
  'Katsina': {
    'Katsina': ['Katsina GRA', 'Kofar Marusa', 'Kofar Sauri'],
    'Funtua': ['Funtua Town', 'Funtua GRA'],
    'Daura': ['Daura Town', 'Daura GRA'],
  },
  'Kebbi': {
    'Birnin Kebbi': ['Birnin Kebbi Town', 'Birnin Kebbi GRA', 'Gwadangaji'],
    'Argungu': ['Argungu Town'],
    'Yauri': ['Yauri Town'],
  },
  'Kogi': {
    'Lokoja': ['Lokoja Town', 'Lokoja GRA', 'Felele', 'Adankolo'],
    'Okene': ['Okene Town', 'Okene GRA'],
    'Kabba/Bunu': ['Kabba Town'],
  },
  'Kwara': {
    'Ilorin West': ['Ilorin GRA', 'Tanke', 'Basin', 'Fate', 'Gaa Akanbi'],
    'Ilorin South': ['Fufu', 'Ita Kure', 'Surulere'],
    'Ilorin East': ['Oke Oyi', 'Ita Amodu'],
    'Offa': ['Offa Town'],
  },
  'Lagos': {
    'Agege': ['Agege Town', 'Oko Oba', 'Mangoro', 'Pen Cinema'],
    'Ajeromi-Ifelodun': ['Ajegunle', 'Layeni', 'Olodi'],
    'Alimosho': ['Ikotun', 'Egbeda', 'Akowonjo', 'Idimu', 'Ipaja', 'Ayobo'],
    'Amuwo-Odofin': ['Festac Town', 'Mile 2', 'Amuwo', 'Apple Junction'],
    'Apapa': ['Apapa GRA', 'Ajegunle', 'Marine Beach', 'Wharf Road'],
    'Badagry': ['Badagry Town', 'Ajara', 'Topo'],
    'Epe': ['Epe Town', 'Eredo', 'Noforija'],
    'Eti-Osa': ['Lekki Phase 1', 'Lekki Phase 2', 'Victoria Island', 'Ikoyi', 'Ajah', 'Banana Island', 'Chevron', 'VGC', 'Sangotedo', 'Eko Atlantic'],
    'Ibeju-Lekki': ['Ibeju Town', 'Lakowe', 'Eleko', 'Abijo', 'Bogije'],
    'Ifako-Ijaiye': ['Ifako', 'Ogba', 'Aguda', 'Iju'],
    'Ikeja': ['GRA Ikeja', 'Allen Avenue', 'Opebi', 'Oregun', 'Alausa', 'Adeniyi Jones', 'Computer Village', 'Maryland'],
    'Ikorodu': ['Ikorodu Town', 'Igbogbo', 'Bayeku', 'Agric'],
    'Kosofe': ['Magodo GRA', 'Ogudu GRA', 'Ketu', 'Ojota', 'Mile 12'],
    'Lagos Island': ['Marina', 'Broad Street', 'TBS', 'Obalende', 'Onikan'],
    'Lagos Mainland': ['Yaba', 'Ebute Metta', 'Oyingbo', 'Iwaya', 'Sabo'],
    'Mushin': ['Mushin Town', 'Idi-Oro', 'Papa Ajao', 'Ladipo'],
    'Ojo': ['Ojo Town', 'Alaba', 'Trade Fair', 'Igbo Elerin'],
    'Oshodi-Isolo': ['Oshodi', 'Isolo', 'Ajao Estate', 'Mafoluku'],
    'Shomolu': ['Shomolu Town', 'Bariga', 'Gbagada', 'Pedro'],
    'Surulere': ['Surulere Town', 'Ojuelegba', 'Adeniran Ogunsanya', 'Western Avenue', 'Aguda', 'Ijesha'],
  },
  'Nasarawa': {
    'Lafia': ['Lafia Town', 'Lafia GRA', 'Shabu'],
    'Keffi': ['Keffi Town', 'Keffi GRA'],
    'Karu': ['Karu Town', 'Jikwoyi', 'Mararaba', 'Nyanya'],
  },
  'Niger': {
    'Chanchaga': ['Minna GRA', 'Tunga', 'Chanchaga'],
    'Suleja': ['Suleja Town', 'Suleja GRA', 'Kwamba'],
    'Bida': ['Bida Town', 'Bida GRA'],
    'Kontagora': ['Kontagora Town', 'Kontagora GRA'],
  },
  'Ogun': {
    'Abeokuta North': ['Abeokuta GRA', 'Kuto', 'Ibara', 'Sapon', 'Onikolobo'],
    'Abeokuta South': ['Oke Ilewo', 'Sapon', 'Adatan', 'Itoku'],
    'Ado-Odo/Ota': ['Ota', 'Sango-Ota', 'Atan', 'Ijoko', 'Ado-Odo'],
    'Ifo': ['Ifo Town', 'Pakuro', 'Coker'],
    'Obafemi Owode': ['Owode', 'Mowe', 'Ofada'],
    'Shagamu': ['Shagamu Town', 'Sabo'],
    'Ijebu Ode': ['Ijebu Ode Town', 'Itoro', 'Imoru'],
    'Ikenne': ['Ikenne Town', 'Iperu'],
  },
  'Ondo': {
    'Akure South': ['Akure Town', 'Alagbaka', 'Oba Ile', 'FUTA'],
    'Akure North': ['Iju', 'Itaogbolu'],
    'Ondo West': ['Ondo Town', 'Yaba Ondo'],
    'Owo': ['Owo Town'],
  },
  'Osun': {
    'Osogbo': ['Osogbo Town', 'Oke-Baale', 'Odi-Olowo', 'GRA Osogbo'],
    'Ife Central': ['Ile-Ife Town', 'Sabo', 'Lagere'],
    'Ilesa East': ['Ilesa Town', 'Bolorunduro'],
    'Iwo': ['Iwo Town'],
  },
  'Oyo': {
    'Ibadan North': ['Bodija', 'Agodi GRA', 'UI', 'Sango', 'Mokola', 'Dugbe'],
    'Ibadan North-West': ['Eleyele', 'Jericho', 'Iyaganku GRA'],
    'Ibadan South-West': ['Ring Road', 'Challenge', 'Oluyole', 'Apata'],
    'Ibadan North-East': ['Iwo Road', 'Bashorun', 'New Gbagi', 'Ashi'],
    'Ibadan South-East': ['Mapo', 'Oje', 'Orita-Challenge'],
    'Akinyele': ['Moniya', 'Ojoo', 'Akobo'],
    'Oluyole': ['Oluyole Estate', 'Idi Ayunre'],
    'Ogbomosho North': ['Ogbomosho Town', 'Sabo'],
    'Oyo West': ['Oyo Town', 'Ojongbodu'],
  },
  'Plateau': {
    'Jos North': ['Jos Town', 'Terminus', 'Bukuru', 'Farin Gada', 'Tudun Wada'],
    'Jos South': ['Bukuru', 'Rayfield', 'Angwan Rogo'],
    'Mangu': ['Mangu Town'],
  },
  'Rivers': {
    'Port Harcourt': ['GRA Phase 1', 'GRA Phase 2', 'Old GRA', 'D Line', 'Borokiri', 'Ada George', 'Trans Amadi', 'Diobu'],
    'Obio/Akpor': ['Rumuosi', 'Elelenwo', 'Rumuokwurusi', 'Choba', 'Rumolumeni', 'Rukpokwu'],
    'Bonny': ['Bonny Town'],
    'Eleme': ['Eleme Town'],
    'Oyigbo': ['Oyigbo Town', 'Afam'],
  },
  'Sokoto': {
    'Sokoto North': ['Sokoto Town', 'Arkilla'],
    'Sokoto South': ['Sokoto GRA', 'Mabera'],
    'Wamako': ['Wamako Town', 'Usmanu Danfodiyo University'],
  },
  'Taraba': {
    'Jalingo': ['Jalingo Town', 'Jalingo GRA', 'Turaki'],
    'Wukari': ['Wukari Town'],
    'Takum': ['Takum Town'],
  },
  'Yobe': {
    'Damaturu': ['Damaturu Town', 'Damaturu GRA', 'Sabon Pegi'],
    'Potiskum': ['Potiskum Town', 'Potiskum GRA'],
    'Nguru': ['Nguru Town', 'Nguru GRA'],
  },
  'Zamfara': {
    'Gusau': ['Gusau Town', 'Gusau GRA', 'Tudun Wada Gusau'],
    'Kaura Namoda': ['Kaura Namoda Town'],
    'Talata Mafara': ['Talata Mafara Town'],
  },
};

// Promise-based API compatibility
export const getStates = () => Promise.resolve({ data: nigeriaStates });
export const getLGAs = (state) => Promise.resolve({ data: stateLGAs[state] || [] });
export const getAreas = (state, lga) => Promise.resolve({ data: lgaAreas[state]?.[lga] || [] });
